version: '3.8'

services:
  db:
    image: postgres:16
    container_name: bank_rest-db
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bank_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser -d bankdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: bank-rest:latest
    container_name: bank_rest-app
    ports:
      - "8080:8080"
    environment:
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: bankpass
      JWT_SECRET: "798jZ7MNcEwhBnHa+Cy9ngHhccGHS1Ra+GnuT5hCdXzs2payX9OAmYc9qSAzvu6bRmkprguPkFokT6h9rGxk7A=="
      JWT_EXPIRATION: "86400000"
      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      db:
        condition: service_healthy
    networks:
      - bank_network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  bank_network:
    driver: bridge