openapi: 3.0.3
info:
  title: Bank Card Management API
  version: 1.0.0
  description: |
    API для управления банковскими картами
    - Аутентификация через JWT
    - Ролевой доступ (ADMIN/USER)

servers:
  - url: http://localhost:8080/api
    description: Development server

paths:
  /cards:
    get:
      tags: [Cards]
      summary: Получить список карт
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Card:
      type: object
      properties:
        id:
          type: integer
          example: 1
        maskedNumber:
          type: string
          example: "**** **** **** 1234"
        owner:
          type: string
          example: "Иван Иванов"
        expirationDate:
          type: string
          format: date
          example: "12/25"
        status:
          type: string
          enum: [ACTIVE, BLOCKED, EXPIRED]
        balance:
          type: number
          format: double
          example: 1500.50